+ Cleaned up some comments. + Verified that all of these preprocessors actually function correctly. + Under Macosx, I can't figure out how to get /usr/bin/cpp to not perform 	precompiled headers, so for now, just use the gcc installed on the 	machine.

diff --git a/imake/ansi_cpp b/imake/ansi_cpp
--- a/imake/ansi_cpp
+++ b/imake/ansi_cpp
@@ -7,34 +7,35 @@ os=`uname -s | sed 's/IRIX.*/IRIX/'`
 
 case "x$os" in
 	xAIX)
-		# good 
 		exec /lib/cpp $*
 		;;
 	xOSF1)
-		# good
 		exec /lib/cpp $*
 		;;
 	xHP-UX)
-		# good
 		# This could also potentially be /usr/ccs/lbin/cpp...
 		exec /lib/cpp.ansi $*
 		;;
 	xIRIX)
+		# stupid irix, this is santctioned by the X distribution.
 		exec cc -E -cckr $*
 		;;
 	xLinux)
 		exec /lib/cpp $*
 		;;
 	xDarwin)
-		exec /usr/bin/cpp $*
+		# /usr/bin/cpp is funny on this OS, I can't figure out how to tell
+		# it not to perform precompilation of the headers. So I'll just use 
+		# the cpp with the installed gcc, which should be fine.
+		exec gcc -E -w -no-cpp-precomp $*
 		;;
-	xSolaris)
+	xSunOS)
 		exec /lib/cpp $*
 		;;
 	*)
-		echo "$0 can't figure out the right cpp to use on $os!"
+		echo "$0 can't figure out the right cpp to use on $os!";
 		exit 1;
 		;;
 esac
-	
-	
+
+exit 1;
